# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode731

podfile: Example/Podfile
before_install:
 - rvm install ruby-2.2.2 #cocoapods 1.0.0 requirement not yet supported ootb by travis
 - gem install cocoapods # Since Travis is not always on latest version
 - gem install xcpretty
 # - pod repo update
 - pod install --project-directory=Example
script:
 - set -o pipefail && xcodebuild test -workspace Example/CWNotificationBanner.xcworkspace -scheme CWNotificationBanner-Example -sdk iphonesimulator8.4 ONLY_ACTIVE_ARCH=NO | xcpretty
 - pod lib lint
